version: "1"

services:
  foreign-exchange-currency-app:
    container_name: "foreign-exchange-currency-app"
    image: onpilot/foreign-exchange-currency-app:latest
    build:
      context: .
    ports:
      - "4173:4173"
    environment:
      - PORT=4173
      # - SERVICE_HOST=http://localhost:4000/api